### ISSUE TITLE
About HDFS_FDW Installation

### ISSUE THREAD

**Issue by pavangadiya** [EnterpriseDB/hdfs_fdw#2]
Hey All,

I am trying to install HDFS_FDW in the following environments.
Environment 1:
PostgreSQL : 9.5.0
OS : Ubuntu 14.04
Thrift : 0.9.2 

Now, I am getting an error while compiling hdfs_fdw.

make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -shared -o hdfs_fdw.so hdfs_client.o hdfs_query.o hdfs_option.o hdfs_deparse.o hdfs_connection.o hdfs_fdw.o -L/usr/local/pgsql/lib -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags  -L/usr/local/thrift/lib/ -Llibhive -lhive  -lfb303 -lstdc++ -lthrift
/usr/bin/ld: //usr/local/lib/libfb303.a(FacebookService.o): relocation R_X86_64_32S against `_ZTVN8facebook5fb30328FacebookService_getName_argsE' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/libfb303.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: **\* [hdfs_fdw.so] Error 1

PS: I provided make clean & make command but unfortunately nothing happens & error remains the same.

Environment 2:
PostgreSQL : 9.5.0
OS : CentOS 7.2
Thrift : 0.9.2 

In this environment, I am getting the same error while compiling hdfs_fdw.

make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_client.o hdfs_client.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_query.o hdfs_query.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_option.o hdfs_option.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_deparse.o hdfs_deparse.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_connection.o hdfs_connection.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_fdw.o hdfs_fdw.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -shared -o hdfs_fdw.so hdfs_client.o hdfs_query.o hdfs_option.o hdfs_deparse.o hdfs_connection.o hdfs_fdw.o -L/usr/local/pgsql/lib -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags  -L/usr/local/thrift/lib/ -Llibhive -lhive  -lfb303 -lstdc++ -lthrift
/usr/bin/ld: /usr/local/lib/libfb303.a(FacebookService.o): relocation R_X86_64_32S against `_ZNSs4_Rep20_S_empty_rep_storageE' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfb303.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make: **\* [hdfs_fdw.so] Error 1

PS: I provided make clean & make command but unfortunately nothing happens & error remains the same.

I think, in both of the environment libfb303 of the thrift library creating the problem.

Could you please help me to resolve this problem.
I am not getting any idea that where I have to look for to resolve this error.
Your help will be much appreciated.

If you say, I can write all the steps which I am following to install HDFS _FDW.

Thank You!!

**Comment by ibrarahmad** [comment]
I am trying to reproduce that issue on my computer.

On Tue, Feb 2, 2016 at 7:55 PM, Pavan Gadiya <notifications@github.com>
wrote:

> Hey All,
>
> I am trying to install HDFS_FDW in the following environments.
> Environment 1:
> PostgreSQL : 9.5.0
> OS : Ubuntu 14.04
> Thrift : 0.9.2
>
> Now, I am getting an error while compiling hdfs_fdw.
>
> make USE_PGXS=1
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -shared -o hdfs_fdw.so hdfs_client.o hdfs_query.o hdfs_option.o
> hdfs_deparse.o hdfs_connection.o hdfs_fdw.o -L/usr/local/pgsql/lib
> -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags
> -L/usr/local/thrift/lib/ -Llibhive -lhive -lfb303 -lstdc++ -lthrift
> /usr/bin/ld: //usr/local/lib/libfb303.a(FacebookService.o): relocation
> R_X86_64_32S against `_ZTVN8facebook5fb30328FacebookService_getName_argsE'
> can not be used when making a shared object; recompile with -fPIC
> //usr/local/lib/libfb303.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> make: *** [hdfs_fdw.so] Error 1
>
> PS: I provided make clean & make command but unfortunately nothing happens
> & error remains the same.
>
> Environment 2:
> PostgreSQL : 9.5.0
> OS : CentOS 7.2
> Thrift : 0.9.2
>
> In this environment, I am getting the same error while compiling hdfs_fdw.
>
> make USE_PGXS=1
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_client.o hdfs_client.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_query.o hdfs_query.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_option.o hdfs_option.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_deparse.o hdfs_deparse.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_connection.o hdfs_connection.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_fdw.o hdfs_fdw.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -shared -o hdfs_fdw.so hdfs_client.o hdfs_query.o hdfs_option.o
> hdfs_deparse.o hdfs_connection.o hdfs_fdw.o -L/usr/local/pgsql/lib
> -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags
> -L/usr/local/thrift/lib/ -Llibhive -lhive -lfb303 -lstdc++ -lthrift
> /usr/bin/ld: /usr/local/lib/libfb303.a(FacebookService.o): relocation
> R_X86_64_32S against `_ZNSs4_Rep20_S_empty_rep_storageE' can not be used
> when making a shared object; recompile with -fPIC
> /usr/local/lib/libfb303.a: could not read symbols: Bad value
> collect2: error: ld returned 1 exit status
> make: *** [hdfs_fdw.so] Error 1
>
> PS: I provided make clean & make command but unfortunately nothing happens
> & error remains the same.
>
> I think, in both of the environment libfb303 of the thrift library
> creating the problem.
>
> Could you please help me to resolve this problem.
> I am not getting any idea that where I have to look for to resolve this
> error.
> Your help will be much appreciated.
>
> If you say, I can write all the steps which I am following to install HDFS
> _FDW.
>
> Thank You!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/hdfs_fdw/issues/2>.
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by pavangadiya** [comment]
Hey Ibrar,

Yeah, Please check the issue & please let me know the resolution of the error. 

Thanks a lot !!

**Comment by pavangadiya** [comment]
Hey Ibrar,

Well, I think the root of the above problem is coming from here. Please check below error.
I am getting an error when I am Compiling and installing fb303.
Please check the issue.

[fb303]# make
make  all-recursive
make[1]: Entering directory `/usr/local/thrift-0.9.1/contrib/fb303'
Making all in .
make[2]: Entering directory `/usr/local/thrift-0.9.1/contrib/fb303'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/usr/local/thrift-0.9.1/contrib/fb303'
Making all in cpp
make[2]: Entering directory `/usr/local/thrift-0.9.1/contrib/fb303/cpp'
/usr/local/bin/thrift -o . -I /usr/local/share  --gen cpp:pure_enums  ../if/fb303.thrift
make  all-am
make[3]: Entering directory `/usr/local/thrift-0.9.1/contrib/fb303/cpp'
g++ -DPACKAGE_NAME=\"libfb303\" -DPACKAGE_TARNAME=\"libfb303\" -DPACKAGE_VERSION=\"20080209\" -DPACKAGE_STRING=\"libfb303\ 20080209\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_BOOST=/\*\*/ -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NETINET_IN_H=1 -I.  -I.. -Igen-cpp -I/usr/local/include/thrift -I/usr/include   -I/include -fPIC  -Wall -O3 -MT FacebookService.o -MD -MP -MF .deps/FacebookService.Tpo -c -o FacebookService.o `test -f 'gen-cpp/FacebookService.cpp' || echo './'`gen-cpp/FacebookService.cpp
mv -f .deps/FacebookService.Tpo .deps/FacebookService.Po
g++ -DPACKAGE_NAME=\"libfb303\" -DPACKAGE_TARNAME=\"libfb303\" -DPACKAGE_VERSION=\"20080209\" -DPACKAGE_STRING=\"libfb303\ 20080209\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_BOOST=/\*\*/ -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NETINET_IN_H=1 -I.  -I.. -Igen-cpp -I/usr/local/include/thrift -I/usr/include   -I/include -fPIC  -Wall -O3 -MT fb303_constants.o -MD -MP -MF .deps/fb303_constants.Tpo -c -o fb303_constants.o `test -f 'gen-cpp/fb303_constants.cpp' || echo './'`gen-cpp/fb303_constants.cpp
mv -f .deps/fb303_constants.Tpo .deps/fb303_constants.Po
g++ -DPACKAGE_NAME=\"libfb303\" -DPACKAGE_TARNAME=\"libfb303\" -DPACKAGE_VERSION=\"20080209\" -DPACKAGE_STRING=\"libfb303\ 20080209\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_BOOST=/\*\*/ -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NETINET_IN_H=1 -I.  -I.. -Igen-cpp -I/usr/local/include/thrift -I/usr/include   -I/include -fPIC  -Wall -O3 -MT fb303_types.o -MD -MP -MF .deps/fb303_types.Tpo -c -o fb303_types.o `test -f 'gen-cpp/fb303_types.cpp' || echo './'`gen-cpp/fb303_types.cpp
mv -f .deps/fb303_types.Tpo .deps/fb303_types.Po
g++ -DPACKAGE_NAME=\"libfb303\" -DPACKAGE_TARNAME=\"libfb303\" -DPACKAGE_VERSION=\"20080209\" -DPACKAGE_STRING=\"libfb303\ 20080209\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_BOOST=/\*\*/ -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NETINET_IN_H=1 -I.  -I.. -Igen-cpp -I/usr/local/include/thrift -I/usr/include   -I/include -fPIC  -Wall -O3 -MT FacebookBase.o -MD -MP -MF .deps/FacebookBase.Tpo -c -o FacebookBase.o FacebookBase.cpp
mv -f .deps/FacebookBase.Tpo .deps/FacebookBase.Po
g++ -DPACKAGE_NAME=\"libfb303\" -DPACKAGE_TARNAME=\"libfb303\" -DPACKAGE_VERSION=\"20080209\" -DPACKAGE_STRING=\"libfb303\ 20080209\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_BOOST=/\*\*/ -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NETINET_IN_H=1 -I.  -I.. -Igen-cpp -I/usr/local/include/thrift -I/usr/include   -I/include -fPIC  -Wall -O3 -MT ServiceTracker.o -MD -MP -MF .deps/ServiceTracker.Tpo -c -o ServiceTracker.o ServiceTracker.cpp
mv -f .deps/ServiceTracker.Tpo .deps/ServiceTracker.Po
rm -f libfb303.a
/usr/bin/ar cru libfb303.a FacebookService.o fb303_constants.o fb303_types.o FacebookBase.o ServiceTracker.o 
ranlib libfb303.a
make[3]: Leaving directory `/usr/local/thrift-0.9.1/contrib/fb303/cpp'
make[2]: Leaving directory `/usr/local/thrift-0.9.1/contrib/fb303/cpp'
Making all in java
make[2]: Entering directory `/usr/local/thrift-0.9.1/contrib/fb303/java'
make[2]: *** No rule to make target `all'.  Stop.
make[2]: Leaving directory `/usr/local/thrift-0.9.1/contrib/fb303/java'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/thrift-0.9.1/contrib/fb303'
make: *** [all] Error 2

**Comment by pavangadiya** [comment]
Well, above mentioned error got solved by configure the fb303 library without java, php & python.
Now, fb303 successfully complied & installed(Only containing c++ library now)

In the next step I am  Compiling HiveClient library (libhive.so).
Here is the output of make & make install. An  error is coming after make install
Please check the issue:

[libhive]# **make**
**g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o thrift/hive_service_constants.o thrift/hive_service_constants.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o thrift/TCLIService_constants.o thrift/TCLIService_constants.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o thrift/TCLIService_server.skeleton.o thrift/TCLIService_server.skeleton.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o thrift/ThriftHive.o thrift/ThriftHive.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o thrift/hive_service_types.o thrift/hive_service_types.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o thrift/TCLIService.o thrift/TCLIService.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o thrift/TCLIService_types.o thrift/TCLIService_types.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o metastore/hive_metastore_constants.o metastore/hive_metastore_constants.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o metastore/hive_metastore_types.o metastore/hive_metastore_types.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o metastore/ThriftHiveMetastore.o metastore/ThriftHiveMetastore.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o ql/queryplan_constants.o ql/queryplan_constants.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o ql/queryplan_types.o ql/queryplan_types.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o odbc/hiveclient.o odbc/hiveclient.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o odbc/hiveclienthelper.o odbc/hiveclienthelper.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o odbc/HiveColumnDesc.o odbc/HiveColumnDesc.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o odbc/HiveResultSet.o odbc/HiveResultSet.cpp
g++  -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/ -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o odbc/HiveRowSet.o odbc/HiveRowSet.cpp
cc  thrift/hive_service_constants.o thrift/TCLIService_constants.o thrift/TCLIService_server.skeleton.o thrift/ThriftHive.o thrift/hive_service_types.o thrift/TCLIService.o thrift/TCLIService_types.o metastore/hive_metastore_constants.o metastore/hive_metastore_types.o metastore/ThriftHiveMetastore.o ql/queryplan_constants.o ql/queryplan_types.o odbc/hiveclient.o odbc/hiveclienthelper.o odbc/HiveColumnDesc.o odbc/HiveResultSet.o odbc/HiveRowSet.o -o libhive.so -shared

[libhive]#** make install**
cp -rf libhive.so /usr/local/pgsql.master/lib

I am not getting what its saying.(In the make install) ...Do i need to make any Symbolic link ?

**Comment by pavangadiya** [comment]
For more understanding ,I am sharing this:

After completing all the steps from documentation(Including errors)
I try to create extension in PotgreSQL, I get the following error.

hadooptest=# CREATE EXTENSION hdfs_fdw;
ERROR:  could not load library "/usr/local/pgsql/lib/hdfs_fdw.so": libthrift-0.9.1.so: cannot open shared object file: No such file or directory

**Comment by ibrarahmad** [comment]
You can place libhive.so in your postgres lib directory or you can do that
by changing the path in Makefile and use make install

On Wed, Feb 3, 2016 at 6:39 PM, Pavan Gadiya <notifications@github.com>
wrote:

> Well, above mentioned error got solved by configure the fb303 library
> without java, php & python.
> Now, fb303 successfully complied & installed(Only containing c++ library
> now)
>
> In the next step I am Compiling HiveClient library (libhive.so).
> Here is the output of make & make install. An error is coming after make
> install
> Please check the issue:
>
> [libhive]# *make*
> **g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o thrift/hive_service_constants.o
> thrift/hive_service_constants.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o thrift/TCLIService_constants.o
> thrift/TCLIService_constants.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o thrift/TCLIService_server.skeleton.o
> thrift/TCLIService_server.skeleton.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o thrift/ThriftHive.o
> thrift/ThriftHive.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o thrift/hive_service_types.o
> thrift/hive_service_types.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o thrift/TCLIService.o
> thrift/TCLIService.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o thrift/TCLIService_types.o
> thrift/TCLIService_types.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o metastore/hive_metastore_constants.o
> metastore/hive_metastore_constants.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o metastore/hive_metastore_types.o
> metastore/hive_metastore_types.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o metastore/ThriftHiveMetastore.o
> metastore/ThriftHiveMetastore.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o ql/queryplan_constants.o
> ql/queryplan_constants.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o ql/queryplan_types.o
> ql/queryplan_types.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o odbc/hiveclient.o odbc/hiveclient.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o odbc/hiveclienthelper.o
> odbc/hiveclienthelper.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o odbc/HiveColumnDesc.o
> odbc/HiveColumnDesc.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o odbc/HiveResultSet.o
> odbc/HiveResultSet.cpp
> g++ -Wno-unused-variable -fPIC -Wall -g -I/usr/local/include/
> -I/usr/local/include//thrift -I/usr/local/include//thrift/fb303 -Ithrift
> -Imetastore -Iodbc -Iodbc2 -Iql -c -o odbc/HiveRowSet.o odbc/HiveRowSet.cpp
> cc thrift/hive_service_constants.o thrift/TCLIService_constants.o
> thrift/TCLIService_server.skeleton.o thrift/ThriftHive.o
> thrift/hive_service_types.o thrift/TCLIService.o thrift/TCLIService_types.o
> metastore/hive_metastore_constants.o metastore/hive_metastore_types.o
> metastore/ThriftHiveMetastore.o ql/queryplan_constants.o
> ql/queryplan_types.o odbc/hiveclient.o odbc/hiveclienthelper.o
> odbc/HiveColumnDesc.o odbc/HiveResultSet.o odbc/HiveRowSet.o -o libhive.so
> -shared
>
> [libhive]#** make install**
> cp -rf libhive.so /usr/local/pgsql.master/lib
>
> I am not getting what its saying.(In the make install) ...Do i need to
> make any Symbolic link ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/hdfs_fdw/issues/2#issuecomment-179237331>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by pavangadiya** [comment]
Hey Ibrar,

I have placed the libthrift-0.9.1.so in my Postgres lib directory.
Finally, It worked out!! :) 

Now, I am able to create extension in Postgres.

hadooptest=# CREATE EXTENSION hdfs_fdw;
CREATE EXTENSION

Thanks a lot for your help. Much appreciated!!

Well, I have one question, If possible Could you please provide me the answer  :

Does hdfs_fdw extension can be worked with Impala as well ?  I want to work with the Impala instead of Hive. The reason for this is that there is a certain overhead involved in running a Map/Reduce job in Hive.

**Comment by ahsanhadi** [comment]
On Wed, Feb 3, 2016 at 9:27 PM, Pavan Gadiya <notifications@github.com>
wrote:

> Hey Ibrar,
>
> I have placed the libthrift-0.9.1.so in my Postgres lib directory.
> Finally, It worked out!! :)
>
> Now, I am able to create extension in Postgres.
>
> hadooptest=# CREATE EXTENSION hdfs_fdw;
> CREATE EXTENSION
>
> Thanks a lot for your help. Much appreciated!!
>
> Well, I have one question, If possible Could you please provide me the
> answer :
>
> Does hdfs_fdw extension can be worked with Impala as well ? I want to work
> with the Impala instead of Hive. The reason for this is that there is a
> certain overhead involved in running a Map/Reduce job in Hive.
>

Not yet, currently we only support connectivity with hiverserver 1 and
hiveserver2. Impala and Hbase support is on the road map.


Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/hdfs_fdw/issues/2#issuecomment-179324518>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by pavangadiya** [comment]
Thanks for the answer Ahsan!
Looking forward to use this extension on Impala & Hbase as well.

**Comment by pavangadiya** [comment]
He y Ibrar & Ahsan,

When I am trying to retrieve the data from HDFS using foreign table of Postgresql, I am getting the following error.
I have checked all my connection settings for host & socket but, problem is still coming.

Please help me to resolve this issue. Thanks!

hadooptest=# select * from fact_tt limit 10;
ERROR:  failed to initialize the HDFS connection object (Could not resolve host for client socket.)

**Comment by ibrarahmad** [comment]
What version of Hive you are using HiveServer1 or HiveServer2?

On Fri, Feb 5, 2016 at 7:38 PM, Pavan Gadiya <notifications@github.com>
wrote:

> Reopened #2 <https://github.com/EnterpriseDB/hdfs_fdw/issues/2>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/hdfs_fdw/issues/2#event-540720379>.
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by pavangadiya** [comment]
I am using HiveServer 2.

**Comment by ibrarahmad** [comment]
You need to start Hiveserver2 with authentication method NOSASL.

hive --service hiveserver2 --hiveconf hive.server2.authentication=NOSASL


On Fri, Feb 5, 2016 at 7:44 PM, Pavan Gadiya <notifications@github.com>
wrote:

> I am using HiveServer 2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/hdfs_fdw/issues/2#issuecomment-180384334>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by pavangadiya** [comment]
Well, I have start Hiveserver2 with authentication method NOSASL. 
I am also able to telnet the host & port number where Hive Service is running.
But, problem remains the same.

**select * from fact_tt limit 10;
ERROR:  failed to initialize the HDFS connection object (Could not resolve host for client socket.)**

**Comment by ahsanhadi** [comment]
Are you using 10000 port number?

On Fri, Feb 5, 2016 at 8:20 PM, Pavan Gadiya <notifications@github.com>
wrote:

> Well, I have start Hiveserver2 with authentication method NOSASL.
> I am also able to telnet the host & port number where Hive Service is
> running.
> But, problem remains the same.
>
>
> *select * from fact_tt limit 10; ERROR: failed to initialize the HDFS
> connection object (Could not resolve host for client socket.)*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/hdfs_fdw/issues/2#issuecomment-180397854>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by pavangadiya** [comment]
Yeah ,I am using port number 10000. I tried with the another port, but its giving the same error every time.

**Comment by pavangadiya** [comment]
I tried all the ways but, error remains same.
Could you please suggest me any other resolution ? 

**select * from fact_tt limit 10;
ERROR: failed to initialize the HDFS connection object (Could not resolve host for client socket.)**
Thank You!

**Comment by ibrarahmad** [comment]
Please create server using this command.


CREATE SERVER hdfs_server
         FOREIGN DATA WRAPPER hdfs_fdw
         OPTIONS (host '127.0.0.1', port '10000', client_type
'hiveserver2');


On Mon, Feb 8, 2016 at 6:11 PM, Pavan Gadiya <notifications@github.com>
wrote:
>
> I tried all the ways but, error remains same.
> Could you please suggest me any other resolution ?
>
> select * from fact_tt limit 10;
> ERROR: failed to initialize the HDFS connection object (Could not resolve
host for client socket.)
> Thank You!
>
> —
> Reply to this email directly or view it on GitHub.




--
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by pavangadiya** [comment]
Hey Ibrar,
I have created the server as you suggested by giving one more attribute client_type 'hiveserver2'.
'hiveserver2').
Now, I am getting the following error.
How to resolve it ? 

**select * from fact_tt limit 10;
WARNING:  terminating connection because of crash of another server process
LINE 1: select * from fact_tt  limit 10;
                      ^
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
**

**Comment by pavangadiya** [comment]
Hey Ibrar & Ahsan,
I have checked the PostgreSQL log file. There, I found the issue in more descriptive way for my error.
I think the problem is with the Thrift host & port. Its not able to resolve host for client socket.
Please check the issue.
In the log file the description of the error is:
**STATEMENT:  select count(*) from fact_1m_par;
Thrift: Tue Feb  9 11:41:31 2016 TSocket::open() getaddrinfo() <Host: ttbm187 Port: 10000>Name or service not known
DBOpenConnection: Could not resolve host for client socket.
ERROR:  failed to initialize the HDFS connection object (Could not resolve host for client socket.)**

**Comment by ibrarahmad** [comment]
Please send your complete test case, i will look at that.

On Tue, Feb 9, 2016 at 6:00 PM, Pavan Gadiya <notifications@github.com>
wrote:

> Hey Ibrar & Ahsan,
> I have checked the PostgreSQL log file. There, I found the issue in more
> descriptive way for my error.
> I think the problem is with the Thrift host & port. Its not able to
> resolve host for client socket.
> Please check the issue.
> In the log file the description of the error is:
>
>
>
> *STATEMENT: select count(*) from fact_1m_par; Thrift: Tue Feb 9 11:41:31
> 2016 TSocket::open() getaddrinfo() Name or service not known
> DBOpenConnection: Could not resolve host for client socket. ERROR: failed
> to initialize the HDFS connection object (Could not resolve host for client
> socket.)*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/hdfs_fdw/issues/2#issuecomment-181854220>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by jeffywu** [comment]
@pavangadiya, I'm running into the same issue you have with fb303, can you post some details about how you were able to resolve it?

**Comment by pavangadiya** [comment]
@jeffywu , Yeah, I also resolved the fb303 issue by putting CXXFLAGS in the Makefile and configured the fb303 library without java, php & python. For me, fb303 was compiled  & installed (with only C++ library).

Well, I would suggest you to place the libthrift-0.9.1.so(or .so file of whatever version of Thrift you are using) in my Postgres lib directory & try to create extension again.The restart of Postgres Server is not needed.

**Comment by jeffywu** [comment]
I had to copy the *.so files into the directory specified by pg_config --libdirs and it worked.
